<?php

/**
 * @var $this Linko_Application_Template|Linko_Template
 */

defined('LINKO') or exit;

?>

<div id="footer">
    <div class="row">
        <div class="eight columns">
            <?php $this->plugin('menu', array('location' => 'footer_links')); ?>
        </div>
	    <div id="copyright" class="four columns text-right">
            &copy; <?php echo Linko::Module()->getSetting('page.site_title'); ?>
	    </div>
    </div>
</div>
<?php echo $this->getFooter(); ?>
</body>
</html>