<?php

/**
 * @var $this Linko_Application_Template|Linko_Template
 */

defined('LINKO') or exit;

?>

<div id="footer">
	<div class="row">
		<div class="twelve columns">
			<ul class="social-links">
				<li class="link-facebook">
					<a href="<?php echo $this->getSetting('facebook_url'); ?>">
						<i class="icon-facebook"></i>
					</a>
				</li>
				<li class="link-twitter">
					<a href="<?php echo $this->getSetting('twitter_url'); ?>">
						<i class="icon-twitter"></i>
					</a>
				</li>
				<li class="link-google-plus">
					<a href="<?php echo $this->getSetting('googleplus_url'); ?>">
						<i class="icon-google-plus"></i>
					</a>
				</li>
			</ul>
		</div>
	</div>
</div>
<?php echo $this->getFooter(); ?>
</body>
</html>