<?php defined('LINKO') or exit;
/**
 * @package Mobile
 * @author Morrison Laju <morrelinko@gmail.com>
 * @var $this Linko_Application_Template
 */
?>

<div class="module">
    <div class="module-header">
        <h3>Re-arrange and Edit Dashboard Links</h3>

        <ul>
            <li>
                <a href="#" class="button">Add Dashboard Link</a>
            </li>
        </ul>
    </div>
    <div class="module-content">
        <div class="no-item">
            <h1><a href="#">@TODO Implement this</a></h1>
            <h3>No Dashboard Links</h3>
            <h5><a href="#">Click here</a> to add dashboard link</h5>
        </div>
    </div>
    <div class="module-footer">

    </div>
</div>