<div id="module-install-goto-upload">
	<p>
		Install a module packaged in .zip files.
	</p>

	<form action="" method="post" enctype="multipart/form-data">
		<p>

		</p>
		<div class="controls">
			<div class="control-item">
				<div class="control-item-data no-label">
					<input id="upload-module-file-js" type="file" name="package" />
					<p>
						Select a linkocms .zip module package to install.
					</p>
				</div>
			</div>

			<div class="control-bottom">
				<input name="upload" id="upload-module-button-js" class="button" type="submit" value="Upload Module" disabled="disabled">
			</div>
		</div>
	</form>

	<?php if($bModulePage): ?>

	<form action="" method="post">
		<input type="hidden" name="module" value="<?php echo $sModule; ?>">
		<div class="module">
		<div class="module-header">
			<h3>Module Information: <?php echo $sModule; ?></h3>
		</div>
		<div class="module-content">
			<table>
				<thead>
				<tr>
					<th colspan="2">General</th>
				</tr>
				</thead>
				<tbody>
					<?php foreach($aInstallInfo['general'] as $sKey => $sValue): ?>
					<tr>
						<td>
							<?php echo Inflector::humanize($sKey); ?>
						</td>
						<td>
							<?php echo $sValue; ?>
						</td>
					</tr>
					<?php endforeach; ?>
				</tbody>
			</table>
			<table>
				<thead>
				<tr>
					<th colspan="2">Requirement</th>
				</tr>
				</thead>
				<tbody>
					<?php if(count($aInstallInfo['requirement'])): ?>
					<?php foreach($aInstallInfo['requirement'] as $aRequirement): ?>
						<tr>
							<td>
								<?php echo $aRequirement['type']; ?>: <b><?php echo $aRequirement['id']; ?></b>
							</td>
							<td>
								<?php if($aRequirement['type'] == 'module'): ?>
									<?php if($aRequirement['module_pass']): ?>
									<span class="module-requirement-pass">Installed</span>
									<?php else: ?>
									<span class="module-requirement-fail">Not Installed</span>
									<?php endif; ?>

									<?php if(isset($aRequirement['version_pass'])): ?>
										<?php if($aRequirement['version_pass'] == true): ?>
										<span class="module-requirement-pass"> Requires at least version <?php echo $aRequirement['version']; ?></span>
										<?php else: ?>
										<span class="module-requirement-fail">Requires at least version <?php echo $aRequirement['version']; ?></span>
										<?php endif; ?>
									<?php endif; ?>

									<?php if(isset($aRequirement['optional'])): ?>
										<span class="module-requirement-optional">Optional</span>
									<?php endif; ?>
								<?php endif; ?>
							</td>
						</tr>
					<?php endforeach; ?>
					<?php else: ?>
					<tr>
						<td>
							<div class="no-item">
								<h4>No Requirements.</h4>
							</div>
						</td>
					</tr>

					<?php endif; ?>
				</tbody>
			</table>

			<?php if($bIsUpgrade): ?>
				<table>
					<thead>
					<tr>
						<th colspan="2">Upgrade Info:</th>
					</tr>
					</thead>
					<tr>
						<td>
							Current Version
						</td>
						<td>
							<?php echo $aUpgradeModule['version']; ?>
						</td>
					</tr>
					<tr>
						<td>
							New Version
						</td>
						<td>
							<?php echo $aModule['version']; ?>
						</td>
					</tr>
					<tr>
						<td>
							Status
						</td>
						<td>
							<?php if(version_compare($aModule['version'], $aUpgradeModule['version'], '<')): ?>
							<span class="module-requirement-fail">
								You are trying to install a version lower than your current version.
							</span>
							<?php elseif(version_compare($aModule['version'], $aUpgradeModule['version'], '==')): ?>
							<span class="module-requirement-optional">
								You are using the same version as the one you want to install. Upgrade is not necessary
							</span>
							<?php else: ?>
							<span class="module-requirement-pass">
								This is a new version. Upgrade
							</span>
							<?php endif; ?>
						</td>
					</tr>
				</table>
			<?php endif; ?>
		</div>

		<div class="module-footer">
			<?php if($bFail): ?>
			<span class="module-requirement-fail">Cannot proceed. Requirements are not met.</span>
			<?php endif; ?>

			<?php if($bIsUpgrade): ?>
			<input name="upgrade" class="button" type="submit" value="Upgrade Module">
			<?php else: ?>
			<input name="install" class="button" type="submit" value="Install Module">
			<?php endif; ?>
		</div>
	</div>
	</form>
	<?php endif; ?>


</div>
<script type="text/javascript">
	$('#upload-module-file-js').on('change', function()
	{
		var file = $(this).val();

		if(file != '')
		{
			$('#upload-module-button-js').removeAttr('disabled');
		}
		else
		{
			$('#upload-module-button-js').attr('disabled', 'disabled');
		}
	});
</script>