<?php

defined('LINKO') or exit();

/**
 * @author LinkoDEV Team
 * @package linkocms
 * @subpackage admincp : controller_template - login.phtml
 * @version 1.0.0
 * @copyright Copyright (c) 2013. All Rights Reserved.
 */
?>

<div class="login-container">
    <div class="login-inner">
        <form action="<?php Linko::Url()->make('self'); ?>" method="post">
            <div class="form-control">
                <label>
                    Email:
                </label>
                <input type="text" class="input-text" name="val[email]" />
            </div>
            
            <div class="form-control">
                <label>
                    Password:
                </label>
                <input type="password" class="input-text" name="val[password]" />
            </div>
            
            <div class="form-control login-button">
                <input type="submit" class="button" name="post[login]" value="Login" />
            </div>
        </form>
    </div>
</div>