<div class="module">
    <div class="module-header">
        <h3>Random Questions</h3>
        <ul>
            <li>
                <a class="button small" href="<?php echo Linko::Url()->make('askq:admincp:random:add')?>">Add Random Question</a>
            </li>
        </ul>
    </div>

    <div class="module-content">

        <table>
            <thead>
             <th style="width: 80%;">
                Question Content
            </th>
            <th style="width: 20%;">
                Action
            </th>
             </thead>
            <tbody>

            <?php foreach($aResult as $key => $value):?>


                <tr>
                    <td><?php echo $value['question_content']?></td>
                    <td>
                        <a href="<?php echo Linko::Url()->make('askq:admincp:random:delete', array('questionid' => $value['question_id']))?>" >Delete</a>
                       <!-- <a href="<?php echo Linko::Url()->make('askq:admincp:random:add', array('questionid' => $value['question_id']))?>">Edit</a>-->
                    </td>
                </tr>
            <?php endforeach?>
            </tbody>
        </table>

        <div class="pager">

            <?php $this->plugin('pager'); ?>
        </div>
    </div>

</div>