<?php

/**
 * @var $this Linko_Application_Template|Linko_Template
 */

defined('LINKO') or exit;

?>

<?php $this->getLayout('snippets/header'); ?>

<div id="content" class="row">
    <div id="leftbar" class="three columns">
        <?php $this->plugin('block', array('position' => 'leftbar')); ?>
    </div>
	<div id="main" class="six columns">
        <?php $this->getLayout('snippets/flash'); ?>
        <?php echo $this->getContent(); ?>
	</div>
	<div id="sidebar" class="three columns">
        <?php $this->plugin('block', array('position' => 'sidebar')); ?>
	</div>
</div>

<?php $this->getLayout('snippets/footer'); ?>
