<?php

defined('LINKO') or exit();

/**
 * @author LinkoDEV Team
 * @package linkocms
 * @subpackage user : controller_template - admincp\role\index.phtml
 * @version 1.0.0
 * @copyright Copyright (c) 2013. All Rights Reserved.
 */
?>

<div class="module">
	<div class="module-header">
		<h3>User Roles</h3>
	</div>

	<table>
		<thead>
		<tr>
            <th style="width: 5%;">
                #ID
            </th>
			<th style="width: 60%;">
				Title
			</th>
			<th style="width: 20%;">
				Type
			</th>
			<th style="width: 15%;">

			</th>
		</tr>
		</thead>

		<tbody>
        <?php foreach($aUserRoles as $aRole): ?>
		<tr>
			<td>
                <?php echo $aRole['role_id']; ?>
			</td>
			<td>
                <?php echo $aRole['role_title']; ?>
			</td>
            <td>
                <?php if($aRole['system'] == 1): ?>
                    System Core
                <?php else: ?>
                    User Defined
                <?php endif; ?>
            </td>
			<td>
				<!--<a href="<?php echo Linko::Url()->make('user:admincp:role:action', array('action' => 'edit', 'id' => $aRole['role_id'])); ?>">Edit</a>
                <?php if($aRole['system'] == 0): ?>
                |
				<a href="<?php echo Linko::Url()->make('user:admincp:role:action', array('action' => 'delete', 'id' => $aRole['role_id'])); ?>">Delete</a>
                <?php endif; ?> -->
			</td>
		</tr>
            <?php endforeach; ?>
		</tbody>
	</table>
</div>
