<?php

defined('LINKO') or exit();

/**
 * @author LinkoDEV Team
 * @package linkocms
 * @subpackage page : block_template - admincp\block-form.phtml
 * @version 1.0.0
 * @copyright Copyright (c) 2013. All Rights Reserved.
 */
?>

<div class="block-form-header"><?php echo $aComponent['module_id']; ?>: <span><?php echo $aComponent['component_label']; ?></span></div>
<form action="" method="post">
    <div class="controls">
        <div class="control-item">
            <div class="control-item-label">
                <label>Block Title:</label>
            </div>
            <div class="control-item-data">
                <input type="text" name="title" value="<?php echo Arr::get($aComponent, 'block_title', ''); ?>" />
            </div>
        </div>

        <?php foreach($aParam as $mParam): ?>
	    <div class="control-item">
		    <div class="control-item-label">
			    <label><?php echo $mParam['label']; ?>:</label>
		    </div>
		    <div class="control-item-data">
			    <?php if($mParam['type'] == 'select'): ?>
                <select name="param[<?php echo $mParam['var']; ?>]">
                    <?php $this->plugin('option', array(
                        'data' => $mParam['data'],
                        'default' => Arr::get($aComponent['block_param'], $mParam['var'], '')
                    )); ?>
                </select>
                <?php elseif($mParam['type'] == 'text'): ?>
                <input type="text" name="param[<?php echo $mParam['var']; ?>]" value="<?php echo Arr::get($aComponent['block_param'], $mParam['var'], ''); ?>" />
                <?php endif; ?>
		    </div>
	    </div>
        <?php endforeach; ?>

	    <div class="control-item">
		    <div class="control-item-label">
			    <label>Dissallow User Roles:</label>
		    </div>
		    <div class="control-item-data">
			    <ul class="option-list">
                    <?php foreach($aUserRoles as $aRole): ?>
				    <li>
					    <input type="checkbox" name="dissallow_access[]"<?php echo(in_array($aRole['role_id'], Arr::get($aComponent, 'dissallow_access', array())) ? ' checked="checked"' : null) ; ?> value="<?php echo $aRole['role_id']; ?>" />
                        <?php echo $aRole['role_title']; ?>
				    </li>
                    <?php endforeach; ?>
			    </ul>
		    </div>
	    </div>

        <div class="control-bottom">
            <input type="submit" class="button small" value="<?php echo $bEdit ? 'Save' : 'Assign'; ?>" />
            <a href="#" class="button cancel small alert">Cancel</a>
        </div>
    </div>
</form>