<?php defined('LINKO') or exit(); ?>

<?php echo $this->getLayout('header', array('layout' => 'login')); ?>

<div id="wrapper">
	<div id="header">
		<div class="row">
			<div class="twelve columns">
				<div class="top-bar">
					<ul id="title" class="left">
						<li class="name"><a href="<?php echo Linko::Url()->make('admincp'); ?>">LinkoCMS</a></li>
					</ul>
				</div>
			</div>
		</div>
	</div>

    <div class="row">
	    <div id="content" class="twelve columns">
            <?php $this->plugin('flash'); ?>
            <?php $this->plugin('error'); ?>
            <?php echo $this->getContent(); ?>
	    </div>
    </div>
</div>
<?php $this->getLayout('footer'); ?>