<?php 

defined('LINKO') or exit();

/**
 * $this here refers to the Linko::Template() namespace
 */
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title><?php echo $this->getTitle(); ?></title>
<?php echo $this->getHeader(); ?>
</head>

<body>
<div id="wrapper-login">
	<div id="header-wrapper" class="clearfix">
    	<div id="header">
        	<h1 id="logo">
        		AdminCP
            </h1>
        </div>
    </div>
    
	<div id="content-wrapper" class="clearfix">
        
    	<div id="content">
            <?php /* Build Flash Message */ ?>
			<?php if(Linko::Flash()->hasMessage()): ?>
            <div class="global-message <?php echo Linko::Flash()->getType(); ?>">
                <?php echo Linko::Flash()->getMessage(); ?>
            </div>
            <?php endif; ?>            
               
            <?php /* Get Controller Content */ ?>    
        	<?php echo $this->getContent(); ?>
        </div>
    </div>
</div>

<?php echo $this->getFooter(); ?>
</body>
</html>