<?php

defined('LINKO') or exit();

/**
 * @author LinkoDEV Team
 * @package linkocms
 * @subpackage locale : controller_template - admincp\index.phtml
 * @version 1.0.0
 * @copyright Copyright (c) 2013. All Rights Reserved.
 */
?>

<div class="module">
    <div class="module-header">
        <h3>Supported Locales</h3>
    </div>
    
    <div class="module-content">
        <table>
            <thead>
                <th style="width: 20%;">
                    ISO Abbreviation
                </th>
                <th style="width: 60%;">
                    Title
                </th>
                <th style="width: 15%;">
                
                </th>
            </thead>
            <tbody>
                <?php foreach($aLanguages as $aLanguage): ?>
                <tr>
                    <td>
                        <?php echo $aLanguage['locale_id']; ?>
                    </td>
                    <td>
                        <?php echo $aLanguage['title']; ?>
                    </td>
                    <td>
                        Edit | Delete
                    </td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>